// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TaskCheckerController from "./task_checker_controller"
application.register("task-checker", TaskCheckerController)
